name: Caren's Notebook
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0625
  lightness: 0.9375
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
