name: Caren's Notebook
favicon: null
layout_spectrum: 0.6364317063707858
typography_spectrum: 0.9763289759866893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19509944296441972
  lightness: 0.9013629893306643
  saturation: 0.4289504187181592
  rhythmicContrast: 0.03292230539955199
purpose: []
